spring.application.name=freightyard
# Tell Spring to use H2 as the database
spring.datasource.url=jdbc:h2:mem:freightdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let JPA automatically create your SQL tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable the H2 console so you can view your database in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
